export default {

	appName: 'Community',

	searchUser: 'Search User',
	done: 'Done',
	enterOTP: 'Enter OTP',
	next: 'Next',
	submit: 'Submit',
	selectMember: 'Select Member',
	privacyPolicy: 'Privacy Policy',




	login: 'Login',
	register: 'Register Now',
	Register: 'Register',
	firstName: 'First Name',
	FullName: 'Full Name',
	lastName: 'Last Name',
	email: 'Email Address',
	phoneNumber: 'Phone Number',
	dontHaveAccount: "Don't have an account?  ",
	enterPhoneNumber: "Enter phone number",
	searchHere: "Search here",
	alreadyAccount: "Already have an account? ",
	enterFirstName: "Enter first name",
	enterLastName: "Enter last name",
	EnterFullName: 'Enter Full Name',

	enterLastName: "Enter last name",
	enterEmailAddress: "Enter email address",
	enterOtp: "Enter OTP",
	verify: "Verify",
	resend: "Resend",
	haveNotReceived: "Have not received OTP? ",
	aboutSchoolInfo: "About School Info",
	CreateBusinesProfile: "Create Business Profile",
	BusinesProfile: "Business Profile",
	SaveProfile: "Save Profile",
	BusinessName: "Business Name",
	BusinessProfile: "Business Profile",
	EnterBusineeName: "Enter Business name",
	Category: "Category",
	SelectCategory: "Select Category",
	SubCategory: "Sub Category",
	EnterCategory: "Enter Sub Category",
	BusinessPhone: "Business Phone",
	EnterBusinessPhone: "Enter Business phone",
	BusinessEmail: "Business Email",
	EnterBusinessEmail: "Enter Business email",
	AddressInfo: "Address Info",
	AddressLine: "Address Line",
	Address: "Address",
	EnterAddress: "Enter Address",
	PersonalProfile: "Personal Profile",
	Search: "Search",
	SelectSchool : "Select School",





	enterMobileNumber: 'Please enter mobile number',
	validMobile: 'Please enter valid mobile number',
	enterPassword: 'Please enter password',
	pleaseLogin: 'Please Login first',
	enterFName: 'Please enter your first name',
	enterLName: 'Please enter your last name',
	enterEmail: 'Please enter email id',
	validEmail: 'Please enter valid email id',
	profile: "Profile",
	change_password: "Change Password",
	confirm: 'Confirm',
	navigate: 'Navigate',
	events: 'Events',
	add_event: 'Add Event',
	add_ads: 'Add New Ads',
	edit_event: "Edit Event",
	view_profile: "View Profile",
	push_now: 'Push Now',
	announcement: "Announcement",
	event: 'Event',
	birthday: "Birthday",
	update_profile: 'Update Profile',
	select_birthdate: 'Select Birthdate',
	special_ask: "Special Ask",
	training: "Training",
	add_training: 'Add Training',
	update_training: 'Update Training',
	addAsk: 'Add Ask',
	updateAsk: 'Update Ask',
	add: 'Add',
	todays_events: "Today's Events",
	view_gain_sheet: 'View Gain Sheet',
	gain_sheet: 'Gain Sheet',
	help: 'Help',
	about_us: 'About Us',
	description: 'Description',
	address: 'Address',
	report: 'Report',
	suggetion: 'Suggetion',
	add_to_contact: 'Add to Contact',
	edit_meeting: "Edit Meeting",
	add_meeting: "Add Meeting",
	delete_account: "Delete Account",
	delete_account_desc: "Are you sure you want to delete your account?",
	alert: "Alert",
	forgot_password: "Forgot Password",


	update: 'Update',
	updateAppDesc: 'Please update your app for better experience',
	chooseOption: 'Please choose your suitable option',

	enter_old_password: "Please enter old password",
	enter_new_password: "Please enter new password alteast 6 character",
	enter_confirm_password: 'Please enter confirm password',
	enter_title: "Please enter title",


	not_valid_password: "New password & confirm password is not match",
	enter_event_name: "Please enter event name",
	enter_event_desc: "Please enter description",
	enter_event_date: "Please select date",
	select_event_image: 'Please upload image',
	please_select_birthdate: "Please Select Birthdate",


	enter_meeting_name: "Please enter meeting title",


	logoutDesc: 'Are you sure you want to logout?',
	turnOnLocation: 'Are you sure you want to turn on your location display in map?',
	turnOffLocation: 'Are you sure you want to turn off your location display in map?',



};